### PR TITLE
Outfit show page

### PR DESCRIPTION
**Pull request by daouasof**
changed the show page for a page with clickable thumbnails, main image and description of the outfit 
image

### CODE REVIEW

**Comment by catagalan-mtl** [comment]
Wow it looks so good! I just have one comment about the code, and it's just about removing the console.logs from the javascript part to clean it a bit, what do you think?

**Comment by catagalan-mtl** [comment]
Oh and one other detailed i notices was that the price says 0.00

**Review by antmarchand — DISMISSED** [review]

**Review by antmarchand — COMMENTED** [review]
Cat going to review further

**Comment by daouasof** [comment]
image

**Comment by daouasof** [comment]
@catagalan-mtl thanks for the review, i took your comments into account and also fixed the case when a user has no avatar

**Review by catagalan-mtl — APPROVED** [review]
looks good! merging

**Pull request merged**
