### PR TITLE
changed devise flash messages in layout

### PR DESCRIPTION
**Pull request by antmarchand**
Made adjustments to views -> layout for devise. Please review.

### CODE REVIEW

**Comment by antmarchand** [comment]
Screenshot 2023-05-30 at 1 47 27 PM

**Comment by antmarchand** [comment]
Screenshot 2023-05-30 at 1 47 27 PM

**Comment by antmarchand** [comment]
Screenshot 2023-05-30 at 1 53 28 PM

**Comment by antmarchand** [comment]
@daouasof Tested, please review.

**Comment by daouasof** [comment]
Perfect !

**Review by daouasof — APPROVED** [review]
great

**Pull request merged**
